---
title: "Untitled"
output: html_document
date: "2025-08-27"
---

Load libraries.

```{r}
library(dplyr)
library(ggplot2)
library(readxl)
library(ggpubr)
```

Read in data.

```{r}
pellet <- read_excel("Female cohort - PO/Fecal pellet number data - female cohort.xlsx")
pellet$Group <- ifelse(pellet$Group == 'Veh (PO)', 'Veh\n(PO)', 'G_50\n(PO)')
pellet$Group <- factor(pellet$Group,
                                levels = c('Veh\n(PO)',
                                           'G_50\n(PO)'))

pellet <- dplyr::rename(pellet, pellet_num=`No. of Fecal Matter at the end of 1hr Activity Chamber`)
```

Plot.

```{r}
ggplot(pellet, aes(x = Group, y = pellet_num)) +
  geom_boxplot(aes(color = Group), fill = NA, outlier.shape = NA, linewidth = 1) +
  geom_point(color = "grey", position = position_jitter(width = 0.1), size = 1) +
  scale_color_manual(values = c("Veh (PO)" = "#E38AB8", "G_50 (PO)" = "#E0B83E")) +
  scale_y_continuous(
    breaks = seq(0, 10, by = 1)
  ) +
  stat_compare_means(
    method = "t.test",
    label = "p.format",
    comparisons = list(c("Veh\n(PO)", "G_50\n(PO)")),
    hide.ns = FALSE
  ) +
  theme_bw() +
  theme(
    legend.position = "none",
    axis.line = element_line(color = "black"),
    axis.text.y = element_text(size = 10, color = "black"),
    axis.text.x = element_text(size = 10, color = "black"),
    axis.title.y = element_text(size = 12, color = "black"),
    axis.title.x = element_blank()
  ) +
  labs(y = "# pellets")

ggsave("Female cohort - PO/fecal_pellet_num.pdf", width = 3, height = 4)
```