---
title: "Untitled"
output: html_document
date: "2026-06-22"
---

Load libraries.

```{r}
library(dplyr)
library(ggplot2)
library(readxl)
library(ggpubr)
```

Read in data.

```{r}
rotarod <- read_excel("Male cohort 3 - PO/Data to plot - cohort 3.xlsx", sheet = "Rotarod_3")
rotarod$`Mouse Group` <- ifelse(rotarod$`Mouse Group` == 'Veh (PO)', 'Veh\n(PO)', 'G_50\n(PO)')
rotarod$`Mouse Group` <- factor(rotarod$`Mouse Group`,
                                levels = c('Veh\n(PO)',
                                           'G_50\n(PO)'))

rotarod <- dplyr::rename(rotarod, latency=`Latency to fall (s)`)
```

Plotting function for each trial.

```{r}
plotting_func <- function(df, trial, ylab,
                          fname, ttl, wid = 2, ht = 2) {
  df <- dplyr::filter(df, Trial == trial)
  ggplot(df, aes(x=`Mouse Group`, y=latency)) +
    geom_boxplot(aes(color = `Mouse Group`), fill = NA, outlier.shape = NA, linewidth = 1) +
    geom_point(color = "grey", position = position_jitter(width = 0.1), size = 1) +
    scale_color_manual(values = c("Veh\n(PO)" = "#008888", "G_50\n(PO)" = "#000080")) +
    stat_compare_means( method = "t.test", label = "p.signif", comparisons = list(c("Veh\n(PO)", "G_50\n(PO)")), hide.ns = FALSE) +
    theme_bw() +
    theme(legend.position = "none",
      axis.line = element_line(color='black'),
      axis.text.y = element_text(size = 8, color = 'black'),
      axis.text.x = element_text(size = 10, color = 'black'),
      axis.title.y = element_text(size = 10, color = 'black'),
      axis.title.x = element_blank()) +
    labs(y = ylab, title = ttl) + ylim(0,50)
  
  ggsave(fname, width = wid, height = ht)
}
```

Apply the plotting function.

```{r}
# 60min_PD_16rpm
plotting_func(rotarod, "60min_PD_16rpm",
              "Latency to fall (s)", "Male cohort 3 - PO/rotarod_60min_PD_16rpm.pdf",
              "60min_PD_16rpm")

# 15min_PD_16rpm
plotting_func(rotarod, "15min_PD_16rpm",
              "Latency to fall (s)", "Male cohort 3 - PO/rotarod_15min_PD_16rpm.pdf",
              "15min_PD_16rpm")

# 15min_PD_32rpm
plotting_func(rotarod, "15min_PD_32rpm",
              "Latency to fall (s)", "Male cohort 3 - PO/rotarod_15min_PD_32rpm.pdf",
              "15min_PD_32rpm")
```

Stats. Really only relevant for 15min_PD_32rpm.

```{r}
# t-test for latency to fall
filtered <- dplyr::filter(rotarod, Trial == "15min_PD_32rpm")
print(t.test(
  dplyr::filter(filtered, `Mouse Group` == 'Veh\n(PO)')$latency,
  dplyr::filter(filtered, `Mouse Group` == 'G_50\n(PO)')$latency
))

# Fisher exact test for fell / did not fall

rotarod_table <- matrix(
  c(8, 7,
    2, 12),
  nrow = 2,
  byrow = TRUE
)

rownames(rotarod_table) <- c("GDCA", "Vehicle")
colnames(rotarod_table) <- c("Fell", "Did_not_fall")

rotarod_table
fisher.test(rotarod_table)
```