---
title: "Untitled"
output: html_document
date: "2025-08-27"
---

Load libraries.

```{r}
library(dplyr)
library(ggplot2)
library(readxl)
library(ggpubr)
```

Read in data.

```{r}
ac_data <- read_excel("Male cohort 1 - RO/Data to plot - cohort 1.xlsx", sheet = "AC_1")
ac_data$`Mouse Group` <- ifelse(ac_data$`Mouse Group` == 'Vehicle', 'Veh\n(RO)', 'G_0.4\n(RO)')
ac_data$`Mouse Group` <- factor(ac_data$`Mouse Group`,
                                levels = c("Veh\n(RO)",
                                           "G_0.4\n(RO)"))
```

Function to plot a variable of interest.

```{r}
plotting_func <- function(df, variable, ylab,
                          fname, wid = 2, ht = 2) {
  df <- dplyr::filter(df, Measure == variable)
  ggplot(df, aes(x=`Mouse Group`, y=Value)) +
    geom_boxplot(aes(color = `Mouse Group`), fill = NA, outlier.shape = NA, linewidth = 1) +
    geom_point(color = "grey", position = position_jitter(width = 0.1), size = 1) +
    scale_color_manual(values = c("Veh\n(RO)" = "#008888", "G_0.4\n(RO)" = "#9f329f")) +
    stat_compare_means( method = "t.test", label = "p.signif", comparisons = list(c("Veh\n(RO)", "G_0.4\n(RO)")), hide.ns = FALSE) +
    theme_bw() +
    theme(legend.position = "none",
      axis.line = element_line(color='black'),
      axis.text.y = element_text(size = 8, color = 'black'),
      axis.text.x = element_text(size = 10, color = 'black'),
      axis.title.y = element_text(size = 10, color = 'black'),
      axis.title.x = element_blank()) +
    labs(y = ylab) + expand_limits(y = max(df$Value) * 1.1)
  
  ggsave(fname, width = wid, height = ht)
}
```

Apply the plotting function.

```{r}
# "Total distance moved (periphery)"
plotting_func(ac_data, "Total distance moved (periphery)",
              "Distance: periphery (cm)", "Male cohort 1 - RO/ac_tot_dist_moved_periphery.pdf")

# "Total distance moved (center)"
plotting_func(ac_data, "Total distance moved (center)",
              "Distance: center (cm)", "Male cohort 1 - RO/ac_tot_dist_moved_center.pdf")

# "Total vertical counts (periphery + center)"
plotting_func(ac_data, "Total vertical counts (periphery + center)",
              "Vertical counts", "Male cohort 1 - RO/ac_tot_vert_counts_periphery_and_center.pdf")

# "Total time in center"
plotting_func(ac_data, "Total time in center",
              "Time in center (s)", "Male cohort 1 - RO/ac_tot_time_in_center.pdf")

# "Latency to center"
plotting_func(ac_data, "Latency to center",
              "Latency to center (s)", "Male cohort 1 - RO/ac_latency_to_center.pdf")
```

Info for supplementary table - record in Stats spreadsheet.

```{r}
stat_calculator <- function(measure) {
  filtered <- dplyr::filter(ac_data, Measure == measure)
  return(t.test(dplyr::filter(filtered, `Mouse Group` == 'Veh\n(RO)')$Value,
       dplyr::filter(filtered, `Mouse Group` == 'G_0.4\n(RO)')$Value))
}

for (meas in unique(ac_data$Measure)) {
  print(meas)
  print(stat_calculator(meas))
}
```