---
title: "Untitled"
output: html_document
date: "2025-08-20"
---

Load libraries.

```{r}
library(dplyr)
library(ggplot2)
library(readxl)
library(data.table)
library(ggpubr)
library(reshape2)
library(Seurat)
library(viridis)
```

Read in single cell data.

Paper:
https://www.nature.com/articles/s41593-019-0491-3
(https://doi.org/10.1038/s41593-019-0491-3)

Aug 22 2025 - bulk downloaded processed data, from: 
https://singlecell.broadinstitute.org/single_cell/study/SCP263/aging-mouse-brain

```{r}
# Read in expression data
expression_data <- fread('../Ximerakis data/SCP263/expression/expression_Aging_mouse_brain_portal_data_updated.txt')

# Read in metadata
metadata <- read.csv('../Ximerakis data/SCP263/metadata/meta_Aging_mouse_brain_portal_data.txt', sep = '\t')

# Subset both metadata and expression data to the cells from the young mice
metadata <- dplyr::filter(metadata, all_cells_by_age == '2-3mo')
expression_data <- tibble::column_to_rownames(expression_data, var = "GENE")
expression_data <- expression_data[,metadata$NAME]
```

Create Seurat object, calculate marker genes.

```{r}
# Make expression data into matrix
expression_data <- as.matrix(expression_data)

# Metadata - make the first column into rownames
# https://satijalab.github.io/seurat-object/reference/CreateSeuratObject.html
metadata <- tibble::column_to_rownames(metadata, var = "NAME")
# Sanity check
stopifnot(identical(colnames(expression_data), rownames(metadata)))

# https://cran.r-project.org/web/packages/SeuratObject/SeuratObject.pdf
# Counts data - Either a matrix-like object with unnormalized data with cells as columns and features as rows or an Assay-derived object
seurat_object <- CreateSeuratObject(counts = expression_data, meta.data = metadata)
# I have processed data though, not raw data
# So these data should not be in the counts layer, but rather in the data layer
# https://satijalab.org/seurat/articles/announcements.html
seurat_object <- SetAssayData(seurat_object, layer = "data", new.data = expression_data)
seurat_object <- SetAssayData(seurat_object, layer = "counts", new.data = NULL)

# Set cell identities
Idents(seurat_object) <- "cell_class"

# Find strong markers
markers_all <- FindAllMarkers(seurat_object,
                              group.by = "ident",
                              layer = "data",
                              only.pos = TRUE,
                              min.pct = 0.25,
                              logfc.threshold = 0.5)

# Filter to significant markers only
markers_sig <- dplyr::filter(markers_all,
                             p_val_adj <= 0.05)

saveRDS(markers_sig, "significant_markers_per_class_ximerakis.rds")
write.table(markers_sig, "significant_markers_per_class_ximerakis.tsv", sep = '\t', quote = FALSE, row.names = FALSE)
```

Read in differential expression results, and merge.

```{r}
deseq_res <- read.csv('deseq2_outputs/tmao_sig.txt', sep = '\t')
# Filter to downregulated genes
deseq_res <- dplyr::filter(deseq_res, log2FoldChange < 0)
deseq_res$direction <- 'Downregulated'
# Retain only the important columns
deseq_res <- dplyr::select(deseq_res, Gene_Name, direction)
# Merge with markers sig
markers_sig <- merge(markers_sig, deseq_res, by.x = 'gene', by.y = 'Gene_Name', all.x = TRUE)
```

How many downregulated markers are there per cell class? Make a plot.

```{r}
# Select important columns
plot_df <- dplyr::select(markers_sig,
                             gene,
                             cluster,
                             direction)
plot_df$downregulated <- ifelse(!is.na(plot_df$direction), TRUE, FALSE)
plot_df <- plot_df %>%
  group_by(cluster) %>%
  summarise(
    n_genes = n(),
    n_down  = sum(downregulated),
    pct_down = 100 * n_down / n_genes
  ) %>%
  arrange(desc(pct_down))

# Assign shorter name
plot_df <- plot_df %>%
  mutate(
    short_name = case_when(
      cluster == "Neuronal_lineage" ~ "Neuron",
      cluster == "Astrocyte_lineage" ~ "Astro",
      cluster == "Ependymal_cells" ~ "Epend",
      cluster == "Vasculature_cells" ~ "Vasc",
      cluster == "Oligodendrocyte_lineage" ~ "Olg",
      cluster == "Immune_cells" ~ "Immune"
    )
  )

plot_df$short_name <- factor(plot_df$short_name,
                          levels = plot_df$short_name)

# Lollipop plot
ggplot(plot_df, aes(x = short_name, y = pct_down)) +
  geom_segment(aes(x = short_name, xend = short_name, y = 0, yend = pct_down),
               color = "#5b45a2", linewidth = 1) +
  geom_point(shape = 21, fill = NA, color = "#5b45a2", size = 3.8, stroke = 1.2) +
  theme_minimal() +
  labs(y = '% Marker Genes Downregulated') +
  theme(axis.line = element_line(color = 'black'),
        axis.title.y = element_text(color = 'black', size = 10),
        axis.title.x = element_blank(),
        axis.text.y = element_text(color = 'black', size = 8),
        axis.text.x = element_text(color = 'black', size = 10),
        panel.grid = element_blank())

ggsave('pc_marker_genes_downregulated_by_tmao_per_class.pdf', height = 3, width = 3.75)
```
