---
title: "Untitled"
output: html_document
date: "2025-07-18"
---

Load libraries.

```{r}
library(dplyr)
library(ggplot2)
library(readxl)
library(scales)
```

Read in data.

```{r}
met_df <- read_excel('Metabolite classes.xlsx')
# Rename columns
colnames(met_df) <- c("Name", "Super Class", "Class", "Sub Class")
```

Define plotting function and plot.

```{r}
plot_bar <- function(df, column_name, highest, ht = 3) {
  counts <- df %>% count(.data[[column_name]])
  max_n <- max(counts$n)
  upper_limit <- ceiling(max_n / 5) * 5
  print(upper_limit)
  
  p <- ggplot(counts, aes(x = reorder(.data[[column_name]], n), y = n)) +
  geom_bar(stat = "identity", fill = "#008888") +
  geom_text(aes(label = n), hjust = -0.1, size = 3) +
  coord_flip() +
  labs(title = column_name,
       x = NULL, y = "# metabolites") +
  scale_y_continuous(
    breaks = seq(0, upper_limit, by = 5),
    limits = c(0, highest)) +
      theme_minimal() +
  theme(panel.grid = element_blank(),            # remove grid lines
    axis.line = element_line(color = "black"), # add axis lines
    axis.ticks = element_line(color = "black"), # add ticks
    axis.text = element_text(size = 12, color = 'black'),
    axis.title = element_text(size = 14, color = 'black'))
  
  ggsave(paste0("Number Metabolites Per ", column_name, '.pdf'), plot = p,
         width = 6, height = ht)
}

# Plot each level
plot_bar(met_df, "Super Class", 15)
plot_bar(met_df, "Class", 10)
plot_bar(met_df, "Sub Class", 10, ht = 4)
```